apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
      tier: frontend
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
      containers:
      - name: flaskapp-container
        image: flaskapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
